### ISSUE TITLE
Jan design feedback

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/covid-science#1]
**Overall**
Already super strong looking, so a lot of this feedback will probably feel really nit-picky! Really love the shift to navy/orange — still commands gravity without the red/black alarmism. 

- [x] Change orange color to be #FF9466 and the mark color to be #036063. The current colors don't quite pass the AAA contrast standards we push for.
- [x] Remove indents from paragraphs to create a clean start edge. This helps when there's text with multiple starting positions on the page (like the graphics).
- [x] Underline all links.
- [x] Add alt text to all images
- [x] Font size should be no smaller than 12px anywhere. There are a couple of places on the first chart and the map timeline where text dips below that size.
- [x] Body copy and methods copy width should be no wider than 720px. You might also benefit from increasing the line-height to 1.65 and the bottom margin to 4rem. That'll help it breathe a bit more, especially for the longer paragraph chunks.

**Section I**
- [x] Since the bar chart text is serif and style like body copy, it should align with the left edge of the body copy.
- [x] Really love the article flow graphics, but the rounded edges make them look like cars in traffic lanes. Maybe style them a little more like an [article icon](https://material.io/resources/icons/?search=paper&icon=article&style=baseline).

**Section II**
- [x] To differentiate the collaboration diagram from regular body copy and make it styled more like the other graphics, try using a sans serif font for the names and titles, both in the list and the diagram.
- [x] Pull the initial black collaboration map of NYC, London, and Barcelona into the same style as the rest of the piece.
- [x] Should you be able to pan around the map? Not sure if it added much to my understand. Maybe disable?

**Section III**
- [x] Feels a little weird to transition to from left aligned body copy to the center aligned graphic steps. Either style the same or style completely different (body copy serif, anything attached to graphics sans)
- [x] Since the last stage of the citation network diagram has tools tips, I expected all steps to function the same and it was a little confusing whether I needed to hover or click for more info and what each interaction would do. Maybe allow hovers on all steps and add in some small direction text for the user to tell them how to interact (hover for more info, click to go to the original article)
- [x] The red color scale in the articles network feels disjointed from the rest of the color scheme. Try building off of the orange color you have.

**Comment by jeffmacinnes** [comment]
@jadiehm these are great edits -- thanks for looking it all over so closely! Nothing here jumps out as undoable for any reason, so I'll give it all a shot!

**Comment by jeffmacinnes** [comment]
@jadiehm could you share the suggested mark color again? the hex is missing one character

**Comment by jeffmacinnes** [comment]
nm, I got it (I think). #036063?

**Comment by jeffmacinnes** [comment]
Oh, ha, it just did the same thing to me. For some reason it truncates the first '0' character

**Comment by jadiehm** [comment]
Weird! I bet github thinks it's an issue and then throws out the leading zero. But yes, it's '#036063'!
