### ISSUE TITLE
feel like the warped text movement be a big vestibular trigger

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/covid-science#4]
I wonder if it can be way more faint/slower? Might be worth testing with someone who is affected by this stuff

**Comment by jeffmacinnes** [comment]
@russellgoldenberg Good call. I pumped the brakes on the text scrolling (~half as fast now) and slowed down the transition animations a bit and made the title text ever so less contrasty on the background. 
[https://the-pudding.github.io/covid-science/](https://the-pudding.github.io/covid-science/) Let me know if you think it should be pulled back even more
